version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/shopper
      GEMINI_API_KEY: AIzaSyDwX7TwxacRql6teWcQl71gdq7hR40qHlg
    volumes:
      - .:/app
    command: ["node", "dist/main.js"]

volumes:
  postgres_data:
